name: cvmhvbn-ucvm-ci

on:
  push:
    branches: [ main ]

jobs:
  cvmhvbn-build-ucvm-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/cvmhvbn/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvmhvbn/target" >> $GITHUB_ENV
### build ucvm(basin) first 
    - id: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: basin
        path: ucvm
    - id: look-around
      run: ( echo " cvmhvbn-ucvm-ci:pwd =>";pwd;
             echo " cvmhvbn-ucvm-ci:UCVM_SRC_PATH =>"$UCVM_SRC_PATH;
             echo " cvmhvbn-ucvm-ci:UCVM_INSTALL_PATH =>"$UCVM_INSTALL_PATH;
             echo " cvmhvbn-ucvm-ci:RUNNER_WORKSPACE =>"$RUNNER_WORKSPACE;
             echo " cvmhvbn-ucvm-ci:github.action_path =>"${{ github.action_path }};)
      shell: bash
    - id: build-ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'cvmhvbn'
         target-model: 'cvmhvbn'
    - id: get-result
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock cvmhvbn away
      run: (rm -rf $RUNNER_WORKSPACE/cvmhvbn/ucvm/work/model/cvmhvbn)
      shell: bash
### build cvmhvbn from github 
    - name: checkout cvmhvbn main
      uses: actions/checkout@v2
      with: 
        path: cvmhvbn
    - name: move it to the right location
      run: (mv cvmhvbn $RUNNER_WORKSPACE/cvmhvbn/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build cvmhvbn as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/cvmhvbn/ucvm/work/model/cvmhvbn; ./.github/scripts/cvmhvbn-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test cvmhvbn validation standalone
      run: (cd $RUNNER_WORKSPACE/cvmhvbn/ucvm/work/model/cvmhvbn; ./.github/scripts/cvmhvbn-test-standalone.sh)
      shell: bash
    - name: test cvmhvbn with ucvm
      run: (cd $RUNNER_WORKSPACE/cvmhvbn/ucvm/work/model/cvmhvbn; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/cvmhvbn-test-ucvm.sh)
      shell: bash
#    - name: Start SSH via Ngrok
#      if: ${{ success() }}
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#            NGROK_TIMEOUT: 3000
#            SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - name: test cvmhvbn under ucvm
      run: (cd $RUNNER_WORKSPACE/cvmhvbn/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash

  cvmhvbn-build-ucvm-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/cvmhvbn/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvmhvbn/target" >> $GITHUB_ENV
### build ucvm(basin) first 
    - id: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: basin
        path: ucvm
    - id: build-ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'cvmhvbn'
         target-model: 'cvmhvbn'
    - id: get-result
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock cvmhvbn away
      run: (rm -rf $RUNNER_WORKSPACE/cvmhvbn/ucvm/work/model/cvmhvbn)
      shell: bash
### build cvmhvbn from github 
    - name: checkout cvmhvbn main
      uses: actions/checkout@v2
      with: 
        path: cvmhvbn
    - name: move it to the right location
      run: (mv cvmhvbn $RUNNER_WORKSPACE/cvmhvbn/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build cvmhvbn as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/cvmhvbn/ucvm/work/model/cvmhvbn; ./.github/scripts/cvmhvbn-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test cvmhvbn standalone
      run: (cd $RUNNER_WORKSPACE/cvmhvbn/ucvm/work/model/cvmhvbn; ./.github/scripts/cvmhvbn-test-standalone.sh)
      shell: bash
    - name: test cvmhvbn with ucvm
      run: (cd $RUNNER_WORKSPACE/cvmhvbn/ucvm/work/model/cvmhvbn; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/cvmhvbn-test-ucvm.sh)
      shell: bash
#    - name: Start SSH via Ngrok
#      if: ${{ success() }}
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#            NGROK_TIMEOUT: 3000
#            SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - name: test cvmhvbn under ucvm
      run: (cd $RUNNER_WORKSPACE/cvmhvbn/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash



